/**
 * RECIPE ROUTES
 * This file handles how AI-generated recipes are saved and searched.
 * Some actions (like Saving) are protected, while others (like Searching) 
 * are public so anyone can see great recipes.
 */

const express = require("express");
const router = express.Router();
const mongoose = require("mongoose");
const Recipe = require("../models/Recipe"); // The blueprint for recipe data
const SavedRecipe = require("../models/SavedRecipe");
const User = require("../models/User");
const auth = require("../middleware/auth"); // Helper for login protection

/**
 * HELPER: IS VALID OBJECT ID
 * Checks if the ID structure is correct before asking MongoDB for it.
 */
const isValidObjectId = (id) => mongoose.Types.ObjectId.isValid(id);

/**
 * HELPER: ESCAPE REGEX
 * Security function: prevents people from typing special symbols in 
 * the search bar that might crash our database query.
 */
const escapeRegex = (string) => string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * SAVE RECIPE (POST /api/recipes)
 * Used when the AI generates a recipe and the frontend wants to save it.
 */
router.post("/", auth, async (req, res) => {
  try {
    // 1. Next.js sends data wrapped in a 'data' object
    if (!req.body.data) {
      return res.status(400).json({ error: "Missing 'data' object in request body" });
    }

    const { data } = req.body;

    // 2. SANITIZE: Delete fields that should be generated by the server, not the user.
    const sanitizedData = { ...data };
    delete sanitizedData._id;
    delete sanitizedData.author;
    delete sanitizedData.createdAt;
    delete sanitizedData.updatedAt;
    delete sanitizedData.__v;

    // 3. SECURE: Set 'author' to the current logged-in user's ID
    const recipeData = {
      ...sanitizedData,
      author: req.userId,
    };

    // 4. Save to MongoDB
    const recipe = new Recipe(recipeData);
    await recipe.save();

    res.status(201).json({ data: recipe });
  } catch (error) {
    if (error.name === "ValidationError") {
      return res.status(400).json({ error: error.message });
    }
    res.status(500).json({ error: error.message });
  }
});

/**
 * SEARCH RECIPES (GET /api/recipes)
 * PUBLIC: Allows any visitor to search for a recipe by title.
 */
router.get("/", async (req, res) => {
  try {
    const query = {};
    
    // Look for a title filter in the URL like ?filters[title][$eqi]=Pizza
    const titleFilter = req.query["filters[title][$eqi]"];

    if (titleFilter) {
      // 1. Clean the search string
      const escapedFilter = escapeRegex(titleFilter);
      // 2. Build a "Case-Insensitive" search (e.g., 'pizza' matches 'PIZZA')
      query.title = { $regex: new RegExp(`^${escapedFilter}$`, "i") };
    }

    // 3. Find all matching recipes
    const recipes = await Recipe.find(query);
    res.json({ data: recipes });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/**
 * GET SINGLE RECIPE (GET /api/recipes/:id)
 * PUBLIC: Fetches full details for one specific recipe.
 */
router.get("/:id", async (req, res) => {
  try {
    if (!isValidObjectId(req.params.id)) {
      return res.status(400).json({ error: "Invalid recipe ID format" });
    }

    const recipe = await Recipe.findById(req.params.id);

    if (!recipe) {
      return res.status(404).json({ error: "Recipe not found" });
    }

    res.json({ data: recipe });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/**
 * DELETE RECIPE (DELETE /api/recipes/:id)
 * PROTECTED: Only the person who created it (author) or an Admin can delete it.
 */
router.delete("/:id", auth, async (req, res) => {
  try {
    if (!isValidObjectId(req.params.id)) {
      return res.status(400).json({ error: "Invalid recipe ID format" });
    }

    const recipe = await Recipe.findById(req.params.id);

    if (!recipe) {
      return res.status(404).json({ error: "Recipe not found" });
    }

    // 1. Check permissions
    const isAdmin = req.user && req.user.role === "admin";
    const isAuthor = recipe.author.toString() === req.userId;

    if (!isAuthor && !isAdmin) {
      return res
        .status(403)
        .json({ error: "Not authorized to delete this recipe" });
    }

    // 2. Perform the deletion
    await Recipe.findByIdAndDelete(req.params.id);
    res.json({ data: { id: req.params.id } });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
