/**
 * RECIPE ROUTES
 * This file handles how AI-generated recipes are saved and searched.
 * Some actions (like Saving) are protected, while others (like Searching) 
 * are public so anyone can see great recipes.
 */

const express = require("express");
const router = express.Router();
const mongoose = require("mongoose");
const Recipe = require("../models/Recipe"); // The blueprint for recipe data
const SavedRecipe = require("../models/SavedRecipe");
const User = require("../models/User");
const auth = require("../middleware/auth"); // Helper for login protection
const rateLimit = require("../middleware/rate-limit"); // New Rate Limiter
const { getGeminiModel } = require("../lib/ai/client");
const { fetchRecipeImage } = require("../lib/ai/image-service");
const { RECIPE_GENERATION_PROMPT, INGREDIENT_RECIPE_SUGGESTIONS_PROMPT } = require("../lib/ai/prompts");
const PantryItem = require("../models/PantryItem");

/**
 * HELPER: IS VALID OBJECT ID
 * Checks if the ID structure is correct before asking MongoDB for it.
 */
const isValidObjectId = (id) => mongoose.Types.ObjectId.isValid(id);

/**
 * HELPER: ESCAPE REGEX
 * Security function: prevents people from typing special symbols in 
 * the search bar that might crash our database query.
 */
const escapeRegex = (string) => string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * HELPER: NORMALIZE TITLE
 * Turns "pizza margherita" into "Pizza Margherita" for consistent DB storage.
 */
function normalizeTitle(title) {
  return title
    .trim()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(" ");
}

/**
 * SAVE RECIPE (POST /api/recipes)
 * Used when the AI generates a recipe and the frontend wants to save it.
 */
router.post("/", auth, async (req, res) => {
  try {
    // 1. Next.js sends data wrapped in a 'data' object
    if (!req.body.data) {
      return res.status(400).json({ error: "Missing 'data' object in request body" });
    }

    const { data } = req.body;

    // 2. SANITIZE: Delete fields that should be generated by the server, not the user.
    const sanitizedData = { ...data };
    delete sanitizedData._id;
    delete sanitizedData.author;
    delete sanitizedData.createdAt;
    delete sanitizedData.updatedAt;
    delete sanitizedData.__v;

    // 3. SECURE: Set 'author' to the current logged-in user's ID
    const recipeData = {
      ...sanitizedData,
      author: req.userId,
    };

    // 4. Save to MongoDB
    const recipe = new Recipe(recipeData);
    await recipe.save();

    res.status(201).json({ data: recipe });
  } catch (error) {
    if (error.name === "ValidationError") {
      return res.status(400).json({ error: error.message });
    }
    res.status(500).json({ error: error.message });
  }
});

/**
 * SEARCH RECIPES (GET /api/recipes)
 * PUBLIC: Allows any visitor to search for a recipe by title.
 */
router.get("/", async (req, res) => {
  try {
    const query = {};
    
    // Look for a title filter in the URL like ?filters[title][$eqi]=Pizza
    const titleFilter = req.query["filters[title][$eqi]"];

    if (titleFilter) {
      // 1. Clean the search string
      const escapedFilter = escapeRegex(titleFilter);
      // 2. Build a "Case-Insensitive" search (e.g., 'pizza' matches 'PIZZA')
      query.title = { $regex: new RegExp(`^${escapedFilter}$`, "i") };
    }

    // 3. Find all matching recipes
    const recipes = await Recipe.find(query);
    res.json({ data: recipes });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/**
 * GET SINGLE RECIPE (GET /api/recipes/:id)
 * PUBLIC: Fetches full details for one specific recipe.
 */
router.get("/:id", async (req, res) => {
  try {
    if (!isValidObjectId(req.params.id)) {
      return res.status(400).json({ error: "Invalid recipe ID format" });
    }

    const recipe = await Recipe.findById(req.params.id);

    if (!recipe) {
      return res.status(404).json({ error: "Recipe not found" });
    }

    res.json({ data: recipe });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/**
 * DELETE RECIPE (DELETE /api/recipes/:id)
 * PROTECTED: Only the person who created it (author) or an Admin can delete it.
 */
router.delete("/:id", auth, async (req, res) => {
  try {
    if (!isValidObjectId(req.params.id)) {
      return res.status(400).json({ error: "Invalid recipe ID format" });
    }

    const recipe = await Recipe.findById(req.params.id);

    if (!recipe) {
      return res.status(404).json({ error: "Recipe not found" });
    }

    // 1. Check permissions
    const isAuthor = recipe.author.toString() === req.userId;

    if (!isAuthor) {
      return res
        .status(403)
        .json({ error: "Not authorized to delete this recipe" });
    }

    // 2. Perform the deletion
    await Recipe.findByIdAndDelete(req.params.id);
    res.json({ data: { id: req.params.id } });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/**
 * GENERATE RECIPE (POST /api/recipes/generate)
 * Checks DB first, if missing, asks Gemini to create it.
 */
router.post("/generate", auth, async (req, res) => {
  try {
    const { recipeName } = req.body;
    if (!recipeName) return res.status(400).json({ error: "Recipe name is required" });

    const normalizedTitle = normalizeTitle(recipeName);
    
    // 1. Check Database FIRST
    // usage of 'i' flag for case insensitive match on the *exact* normalized title
    // but the regex filter in search uses escapeRegex. Here we want exact match.
    // simpler: search by normalized title string if we store it normalized.
    // existing code: filters[title][$eqi]=...
    
    // Let's first look for Case-Insensitive partial match to find if it exists?
    // The frontend logic used: filters[title][$eqi]=normalizedTitle
    const existingRecipe = await Recipe.findOne({ 
      title: { $regex: new RegExp(`^${escapeRegex(normalizedTitle)}$`, "i") } 
    });

    if (existingRecipe) {
      // Check if saved by user
      const savedEntry = await SavedRecipe.findOne({
        user: req.userId,
        recipe: existingRecipe._id
      });
      
      return res.json({
        success: true,
        recipe: existingRecipe,
        recipeId: existingRecipe._id,
        isSaved: !!savedEntry,
        isPro: req.user.subscriptionTier === "pro",
        fromDatabase: true,
        message: "Recipe loaded from database",
      });
    }

    // 2. Generate with Gemini AI
    const model = getGeminiModel("gemini-2.0-flash");
    const prompt = RECIPE_GENERATION_PROMPT(normalizedTitle);

    const result = await model.generateContent(prompt);
    const text = result.response.text();

    let recipeData;
    try {
      const cleanText = text.replace(/```json\n?|```\n?/g, "").trim();
      recipeData = JSON.parse(cleanText);
    } catch (parseError) {
      console.error("Failed to parse Gemini response:", text);
      return res.status(500).json({ error: "Failed to generate recipe via AI" });
    }

    // Ensure metadata
    recipeData.title = normalizedTitle;
    const category = ["breakfast", "lunch", "dinner", "snack", "dessert"].includes(recipeData.category?.toLowerCase())
      ? recipeData.category.toLowerCase() : "dinner";
    const validCuisines = ["italian", "chinese", "mexican", "indian", "american", "thai", "japanese", "mediterranean", "french", "korean", "vietnamese", "spanish", "greek", "turkish", "moroccan", "brazilian", "caribbean", "middle-eastern", "british", "german", "portuguese", "other"];
    const cuisine = validCuisines.includes(recipeData.cuisine?.toLowerCase()) ? recipeData.cuisine.toLowerCase() : "other";

    // 3. Fetch Image
    const imageUrl = await fetchRecipeImage(normalizedTitle);

    // 4. Save to Database
    const newRecipe = new Recipe({
        title: normalizedTitle,
        description: recipeData.description,
        cuisine,
        category,
        ingredients: recipeData.ingredients,
        instructions: recipeData.instructions,
        prepTime: Number(recipeData.prepTime),
        cookTime: Number(recipeData.cookTime),
        servings: Number(recipeData.servings),
        nutrition: recipeData.nutrition,
        tips: recipeData.tips,
        substitutions: recipeData.substitutions,
        imageUrl: imageUrl || "",
        isPublic: true,
        author: req.userId, // User who triggered generation is the "author"
    });

    await newRecipe.save();

    res.status(201).json({
      success: true,
      recipe: newRecipe,
      recipeId: newRecipe._id,
      isSaved: false,
      isPro: req.user.subscriptionTier === "pro",
      fromDatabase: false,
      message: "Recipe generated and saved successfully!",
    });

  } catch (error) {
    console.error("Error in generate:", error);
    res.status(500).json({ error: error.message || "Internal Server Error" });
  }
});

/**
 * SUGGEST RECIPES (POST /api/recipes/suggest)
 * "Cook with what you have"
 * PROTECTED & RATE LIMITED
 */
router.post("/suggest", auth, rateLimit("suggestion"), async (req, res) => {
  try {
    // 1. Fetch User's Pantry
    const pantryItems = await PantryItem.find({ owner: req.userId });
    
    if (!pantryItems || pantryItems.length === 0) {
      return res.status(200).json({ 
        success: false, 
        message: "Your pantry is empty. Add ingredients first!" 
      });
    }

    const ingredientsList = pantryItems.map((item) => item.name).join(", ");

    // 2. Ask Gemini
    const model = getGeminiModel("gemini-2.0-flash");
    const prompt = INGREDIENT_RECIPE_SUGGESTIONS_PROMPT(ingredientsList);

    const result = await model.generateContent(prompt);
    const text = result.response.text();

    let recipeSuggestions;
    try {
      const cleanText = text.replace(/```json\n?|```\n?/g, "").trim();
      recipeSuggestions = JSON.parse(cleanText);
    } catch (parseError) {
      console.error("Failed to parse Gemini suggestions:", text);
      return res.status(500).json({ error: "Failed to generate suggestions" });
    }

    // 3. Find images for suggestions
    const recipesWithImages = await Promise.all(
      recipeSuggestions.map(async (recipe) => {
        const imageUrl = await fetchRecipeImage(recipe.title);
        return { ...recipe, imageUrl };
      }),
    );

    res.json({
      success: true,
      recipes: recipesWithImages,
      ingredientsUsed: ingredientsList,
      message: `Found ${recipeSuggestions.length} recipes you can make!`,
    });

  } catch (error) {
    console.error("Error in suggest:", error);
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
